on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack -c Release IGDB/IGDB.csproj /p:Version=${VERSION} --output .
      - name: Push
        run: dotnet nuget push gaseous.IGDB.${VERSION}.nupkg --source "https://nuget.pkg.github.com/gaseous-project/index.json" --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGETKEY }}
      - name: Push to NuGet
        run: dotnet nuget push gaseous.IGDB.${VERSION}.nupkg --api-key ${{secrets.NUGETPUBLISHKEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
