on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-preview[0-9]"
      - "[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack -c Release IGDB/IGDB.csproj /p:Version=${VERSION} --output .
      - name: Push
        run: dotnet nuget push IGDB.${VERSION}.nupkg --source "https://nuget.pkg.github.com/gaseous-project/index.json" --api-key ${NUGETKEY}
        env:
          NUGET_TOKEN: ${{ secrets.NUGETKEY }}
